### PR TITLE
Keywords Now

### PR DESCRIPTION
**Pull request by fauno**
Supports "Features" that behave like books but belong to another submenu

### CODE REVIEW

**Comment by northgardner** [comment]
How do I see this?

**Comment by fauno** [comment]
At https://keywords.sutty.nl

**Comment by northgardner** [comment]
A few comments:
1. We should remove the colon (":") when Keywords Now has it's own line on https://keywords.sutty.nl/what-happened-on-january-6-2021/
2. On each essay, under the title it says "BOOK KEYWORDS FOR WHAT HAPPENED ON JANUARY 6, 2021?" Can we change book to "FEATURE" and then have the full title "Keywords Now: What Happened on January 6, 2021?"
3. Similarly, the Cite button should produce a citation with "Keywords Now: What Happened on January 6, 2021?" not "Keywords for..."
4. If the essay doesn't have a Works Cited page, there shouldn't be a link.

**Comment by fauno** [comment]
Hi, I'm uploading a new build for the items you mentioned, except the
citation.  I'll fix that and upload the new Keywords Now feature in a
couple hours.

**Pull request merged**
